version: "3.8"

services:
  acms-api:
    image: artcom/acms-api:v3.6.0
    environment:
      - REPO_URI=http://acms-config/
      - PORT=80
      - ACMS_API_VAR_BACKEND_HOST=${ACMS_API_VAR_BACKEND_HOST}
    depends_on:
      - acms-config
    restart: unless-stopped

  acms-assets:
    image: artcom/acms-assets:v1.3.6
    volumes:
      - ${ASSETS}:/var/www/webdav
    restart: unless-stopped

  acms-config:
    image: artcom/acms-config:v1.4.1
    volumes:
      - type: volume
        source: config
        target: /srv/config
    restart: unless-stopped

volumes:
  config:
