version: "3.2"

services:
  api:
    image: artcom/git-json-api:2.7.1
    environment:
      - REPO_URI=http://content-repo/
      - BACKEND_HOST=${HOST}
      - BODY_SIZE_LIMIT=10mb
      - PORT=80
    depends_on:
      - content-repo
    ports:
      - 81:80

  asset-server:
    build: ./git-json-cms-asset-server
    volumes:
      - /srv/assets:/var/www/webdav
    ports:
      - 82:80

  content-repo:
    build: ./git-json-cms-content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content
    ports:
      - 83:80

  frontend:
    build:
      context: ./git-json-cms-frontend
    environment:
      - ASSET_SERVER_URI=http://${HOST}:82
      - CONFIG_SERVER_URI=http://${HOST}:81
      - CMS_CONFIG_PATH=cmsConfig
      - PORT=80
    ports:
      - 80:80
volumes:
  content:
