version: "3.2"

services:
  api:
    image: "artcom/git-json-api:latest"
    environment:
      - REPO_URI=http://content-repo/
      - BODY_SIZE_LIMIT=1mb
      - PORT=80
    depends_on:
      - content-repo
    ports:
      - 81:80

  asset-server:
    build: ./git-json-cms-asset-server
    volumes:
      - type: volume
        source: assets
        target: /var/www/webdav
    ports:
      - 82:80

  content-repo:
    build: ./git-json-cms-content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content
    ports:
      - 83:80

  frontend:
    build:
      context: ./git-json-cms-frontend
    environment:
      GIT_JSON_API_URI: http://localhost:81
      ASSET_SERVER_URI: http://localhost:82

volumes:
  content:
  assets:
