version: "3.8"

services:
  gateway:
    image: nginx:1.19.6
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_SERVER_NAME=${HOST}
    volumes:
      - ./gateway/templates:/etc/nginx/templates
      - ./gateway/locations:/etc/nginx/conf.d/locations
      - ${CERTIFICATE}:/etc/ssl/certs/server.crt
      - ${KEY}:/etc/ssl/private/server.key
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - config-server
      - asset-server
      - content-repo
    restart: unless-stopped
