version: "3.2"

services:
  api:
    image: artcom/git-json-api:2.7.2
    environment:
      - REPO_URI=http://content-repo/
      - BACKEND_HOST=${HOST}
      - BODY_SIZE_LIMIT=10mb
      - PORT=80
    depends_on:
      - content-repo
    ports:
      - 81:80
    restart: unless-stopped

  asset-server:
    image: artcom/git-json-cms-asset-server:1.0.0
    volumes:
      - /srv/assets:/var/www/webdav
    ports:
      - 82:80
    restart: unless-stopped

  content-repo:
    build: ./git-json-cms-content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content
    ports:
      - 83:80
    restart: unless-stopped

  frontend:
    build:
      context: ./git-json-cms-frontend
    environment:
      - ASSET_SERVER_URI=http://${HOST}:82
      - CONFIG_SERVER_URI=http://${HOST}:81
      - CMS_CONFIG_PATH=cmsConfig
      - PORT=80
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  content:
