version: "3.2"

services:
  nginx:
    build: ./nginx
    volumes:
      - type: volume
        source: content
        target: /srv/content
    depends_on:
      - content-repo

  content-repo:
    build: ./content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content
    tty: true

  git-json-api:
    image: "artcom/git-json-api:latest"
    environment:
      - REPO_URI=http://nginx/git/content/
    depends_on:
      - nginx
    links:
      - nginx

  web:
    build: .
    depends_on:
      - git-json-api

volumes:
  content:
