version: "3.8"

services:
  api:
    image: artcom/acms-api:2.7.2
    environment:
      - REPO_URI=http://config/
      - BACKEND_HOST=${HOST}
      - BODY_SIZE_LIMIT=10mb
      - PORT=80
    depends_on:
      - config
    restart: unless-stopped

  assets:
    image: artcom/acms-assets:1.1.0
    volumes:
      - ${ASSETS}:/var/www/webdav
    restart: unless-stopped

  config:
    image: artcom/acms-config:1.1.0
    volumes:
      - type: volume
        source: content
        target: /srv/content
    restart: unless-stopped

volumes:
  content:
