version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_SERVER_NAME=${HOST}
      - NGINX_CERTIFICATE=/etc/nginx/certs/server.crt
      - NGINX_KEY=/etc/nginx/certs/server.key
    volumes:
      - ${CERTIFICATE}:/etc/nginx/certs/server.crt
      - ${KEY}:/etc/nginx/certs/server.key
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - api
      - asset-server
      - content-repo
    restart: unless-stopped

  api:
    image: artcom/git-json-api:2.7.2
    environment:
      - REPO_URI=http://content-repo/
      - BACKEND_HOST=${HOST}
      - BODY_SIZE_LIMIT=10mb
      - PORT=80
    depends_on:
      - content-repo
    restart: unless-stopped

  asset-server:
    image: artcom/git-json-cms-asset-server:1.0.0
    volumes:
      - ${ASSETS}:/var/www/webdav
    restart: unless-stopped

  content-repo:
    image: artcom/git-json-cms-content-repo:1.0.1
    volumes:
      - type: volume
        source: content
        target: /srv/content
    restart: unless-stopped

volumes:
  content:
