version: "3.8"

services:
  gateway:
    image: nginx:1.25
    ports:
      - 80:80
    environment:
      - NGINX_SERVER_NAME=${HOST}
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/templates/server-http.conf.template:/etc/nginx/templates/server.conf.template:ro
      - ./gateway/locations/acms-ui.conf:/etc/nginx/conf.d/locations/acms-ui.conf:ro
      - ./gateway/locations/services:/etc/nginx/conf.d/locations/services:ro
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - acms-api
      - acms-assets
      - acms-config
    restart: unless-stopped
