version: "3.8"

services:
  gateway:
    image: nginx:1.19.6
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_SERVER_NAME=${HOST}
    volumes:
      - ./gateway/templates/server.conf.template:/etc/nginx/templates/server.conf.template:ro
      - ./gateway/locations/acms-ui.conf:/etc/nginx/conf.d/locations/acms-ui.conf:ro
      - ./gateway/locations/services:/etc/nginx/conf.d/locations/services:ro
      - ./ui:/usr/share/nginx/html:ro
      - ${CERTIFICATE}:/etc/ssl/certs/server.crt:ro
      - ${KEY}:/etc/ssl/private/server.key:ro
      - ${DHPARAM}:/etc/ssl/dhparam.pem:ro
    depends_on:
      - acms-api
      - acms-assets
      - acms-config
    restart: unless-stopped
