version: "3.8"

services:
  acms-api:
    image: artcom/acms-api:3.3.0
    environment:
      - REPO_URI=http://acms-config/
      - BACKEND_HOST=${HOST}
      - BODY_SIZE_LIMIT=10mb
      - PORT=80
    depends_on:
      - acms-config
    restart: unless-stopped

  acms-assets:
    image: artcom/acms-assets:1.1.0
    volumes:
      - ${ASSETS}:/var/www/webdav
    restart: unless-stopped

  acms-config:
    image: artcom/acms-config:1.1.1
    volumes:
      - type: volume
        source: config
        target: /srv/config
    restart: unless-stopped

volumes:
  config:
