version: "3.2"

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile.development
    volumes:
      - ./cms:/usr/src/app
      - /usr/src/app/node_modules
