name: acms

services:
  acms-api:
    image: artcom/acms-api:v3.13
    environment:
      - REPO_URI=http://acms-config/
      - PORT=80
      - ACMS_API_VAR_BACKEND_HOST
    depends_on:
      - acms-config
    restart: unless-stopped

  acms-assets:
    image: artcom/acms-assets:v1.4
    volumes:
      - type: volume
        source: assets
        target: /var/www/webdav
    restart: unless-stopped

  acms-config:
    image: artcom/acms-config:v1.10
    volumes:
      - type: volume
        source: config
        target: /srv/config
    restart: unless-stopped

volumes:
  config:
  assets:
