FROM node:latest

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
COPY webpack.config.js /usr/src/app/webpack.config.js
RUN npm install

# start app
CMD ["npm", "run", "watch"]
